# Must exist before Deployments/Statefulsets
# kubectl apply -f mongo-secret.yaml
# 
# equivalent to `kubectl apply -f mongo-secret.yaml -n default`
# where resources are created in default namespace
#
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ3Bhc3N3b3Jk
